// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASiKg9DBP7gZLrjwGLGnKvwjIAL7Ax-RQ',
    appId: '1:415127237966:web:445037a3df74ae72011a1f',
    messagingSenderId: '415127237966',
    projectId: 'flutterchatappwithfirebase',
    authDomain: 'flutterchatappwithfirebase.firebaseapp.com',
    storageBucket: 'flutterchatappwithfirebase.appspot.com',
    measurementId: 'G-VZWNJZ0V20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgOFziOvLlErjkvLVEiFhl3hEFfYof0o',
    appId: '1:415127237966:android:2609bbb0d76f0194011a1f',
    messagingSenderId: '415127237966',
    projectId: 'flutterchatappwithfirebase',
    storageBucket: 'flutterchatappwithfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF3XQBTJejAuW7EMx7iNAokOi13ex3Ivs',
    appId: '1:415127237966:ios:78486f896ec5a408011a1f',
    messagingSenderId: '415127237966',
    projectId: 'flutterchatappwithfirebase',
    storageBucket: 'flutterchatappwithfirebase.appspot.com',
    iosClientId: '415127237966-j0icacl00oq00d47libo29f7rahm69dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchatappwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF3XQBTJejAuW7EMx7iNAokOi13ex3Ivs',
    appId: '1:415127237966:ios:3817ecd1dc4a1a73011a1f',
    messagingSenderId: '415127237966',
    projectId: 'flutterchatappwithfirebase',
    storageBucket: 'flutterchatappwithfirebase.appspot.com',
    iosClientId: '415127237966-l1n0jk8jstgbrqchk43ttqmepc0ijttn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchatappwithfirebase.RunnerTests',
  );
}
